import { useEffect, useState } from "react"
import { Link, useNavigate } from "react-router-dom"
import { LogOut, UserRound } from "lucide-react"
import api from "../api/axios"
import { useAuthStore } from "../store/auth"
import { useThemeStore } from "../store/theme"
import { getGamification } from "../api/auth"
import Loader from "../components/Loader"
import { mediaUrl } from "../utils/media"

export default function Profile() {
  const navigate = useNavigate(); const { theme } = useThemeStore(); const dark = theme === "dark"
  const user = useAuthStore((state) => state.user); const setUser = useAuthStore((state) => state.setUser); const logout = useAuthStore((state) => state.logout)
  const [loading, setLoading] = useState(!user); const [attempts, setAttempts] = useState([]); const [gamification, setGamification] = useState(null)
  useEffect(() => { if (!user) api.get("/auth/me/").then((res) => setUser(res.data)).catch(() => navigate("/login")).finally(() => setLoading(false)); api.get("/quizzes/my-attempts/").then((res) => setAttempts(res.data)).catch(() => {}); getGamification().then((res) => setGamification(res.data)).catch(() => {}) }, [user, setUser, navigate])
  if (loading) return <Loader />
  if (!user) return null
  return <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12"><div className={`rounded-2xl border p-6 sm:p-8 mb-6 ${dark ? "bg-[#0e1726] border-white/8" : "bg-white border-slate-200 shadow-sm"}`}><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-full overflow-hidden bg-blue-600/15 text-blue-500 flex items-center justify-center">{user.avatar ? <img src={mediaUrl(user.avatar)} alt={user.telegram_full_name || user.username} className="w-full h-full object-cover" /> : <UserRound size={26} />}</div><div className="flex-1"><h1 className={`text-2xl font-extrabold ${dark ? "text-white" : "text-slate-900"}`}>{user.telegram_full_name || user.first_name || user.username}</h1><p className={dark ? "text-slate-400" : "text-slate-500"}>{user.telegram_username ? `@${user.telegram_username}` : `@${user.username}`}</p></div><button onClick={() => { logout(); navigate("/") }} className="inline-flex items-center gap-2 text-sm text-rose-500"><LogOut size={15} /> Chiqish</button></div></div>{gamification && <div className={`rounded-2xl border p-6 mb-6 ${dark ? "bg-[#0e1726] border-white/8" : "bg-white border-slate-200 shadow-sm"}`}><div className="flex flex-wrap items-end justify-between gap-4 mb-4"><div><p className="text-xs text-blue-500 font-semibold">LEVEL {gamification.level}</p><p className={`text-3xl font-black ${dark ? "text-white" : "text-slate-900"}`}>{gamification.total_points} XP</p></div><p className="text-sm text-orange-500 font-bold">🔥 {gamification.current_streak} kun streak</p></div><div className={`h-2 rounded-full ${dark ? "bg-white/10" : "bg-slate-100"}`}><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.min(100, (gamification.total_points % 100))}%` }} /></div>{gamification.badges?.length > 0 && <div className="flex flex-wrap gap-2 mt-5">{gamification.badges.map((badge) => <span key={badge.code} title={badge.description} className={`px-3 py-1.5 rounded-lg text-sm ${dark ? "bg-white/5 text-slate-200" : "bg-slate-100 text-slate-700"}`}>{badge.icon} {badge.name}</span>)}</div>}</div>}<div className={`rounded-2xl border p-6 ${dark ? "bg-[#0e1726] border-white/8" : "bg-white border-slate-200 shadow-sm"}`}><div className="flex items-center justify-between mb-4"><h2 className={`text-lg font-bold ${dark ? "text-white" : "text-slate-900"}`}>Test natijalari</h2><Link to="/leaderboard" className="text-sm text-blue-500 font-semibold">Leaderboard</Link></div>{attempts.length ? <div className="space-y-2">{attempts.map((attempt) => <Link key={attempt.id} to={`/tests/${attempt.quiz_slug}`} className={`flex items-center justify-between p-3 rounded-xl ${dark ? "hover:bg-white/5" : "hover:bg-slate-50"}`}><span className={dark ? "text-slate-300" : "text-slate-700"}>{attempt.quiz_title}</span><span className={`font-bold ${attempt.passed ? "text-emerald-500" : "text-amber-500"}`}>{attempt.score}%</span></Link>)}</div> : <p className={dark ? "text-slate-500" : "text-slate-400"}>Hali test ishlanmagan.</p>}</div></div>
}
